### ISSUE TITLE
不能搜索

### ISSUE THREAD

**Issue by triumph** [lxw15337674/aipan-netdisk-search-plus#1]
[POST] "https://hunhepan.com/open/search/disk": 403 Forbidden

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)
  at Object.handler (server/api/sources/hh/search.ts:21:1)
  at async node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2249:7)

**Comment by lxw15337674** [comment]
![image](https://github.com/lxw15337674/aipan-netdisk-search-plus/assets/19898669/2e1bad7e-f9d8-4ee0-9084-420aafa1389e)
我这可以，你怎么操作的
